/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#ffb77d',
        'on-primary': '#ffffff',
        'on-tertiary': '#ffffff',
        'secondary-fixed-dim': '#68dba9',
        'tertiary': '#703a00',
        'on-secondary-fixed-variant': '#005137',
        'on-error-container': '#93000a',
        'outline-variant': '#c7c4d8',
        'background': '#faf8ff',
        'inverse-on-surface': '#eef0ff',
        'surface-bright': '#faf8ff',
        'tertiary-fixed': '#ffdcc3',
        'outline': '#777587',
        'error-container': '#ffdad6',
        'surface-container-high': '#e2e7ff',
        'on-secondary': '#ffffff',
        'surface-tint': '#4d44e3',
        'surface-container-highest': '#dae2fd',
        'secondary-fixed': '#85f8c4',
        'surface-container': '#eaedff',
        'on-surface-variant': '#464555',
        'surface': '#faf8ff',
        'surface-container-low': '#f2f3ff',
        'secondary-container': '#82f5c1',
        'inverse-primary': '#c3c0ff',
        'primary-container': '#4f46e5',
        'secondary': '#006c4a',
        'error': '#ba1a1a',
        'on-tertiary-fixed-variant': '#6e3900',
        'on-background': '#131b2e',
        'on-error': '#ffffff',
        'on-secondary-container': '#00714e',
        'primary-fixed': '#e2dfff',
        'on-tertiary-fixed': '#2f1500',
        'primary': '#3525cd',
        'primary-fixed-dim': '#c3c0ff',
        'on-primary-fixed-variant': '#3323cc',
        'surface-container-lowest': '#ffffff',
        'inverse-surface': '#283044',
        'on-surface': '#131b2e',
        'on-tertiary-container': '#ffd2b1',
        'surface-variant': '#dae2fd',
        'on-primary-fixed': '#0f0069',
        'on-primary-container': '#dad7ff',
        'tertiary-container': '#934e00',
        'on-secondary-fixed': '#002114',
        'surface-dim': '#d2d9f4'
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px'
      },
      spacing: {
        'space-xl': '2.5rem',
        'gutter': '1.5rem',
        'space-sm': '0.5rem',
        'space-xs': '0.25rem',
        'margin-mobile': '1rem',
        'space-lg': '1.5rem',
        'margin': '2rem',
        'gutter-mobile': '1rem',
        'space-md': '1rem'
      },
      fontFamily: {
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'label-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'body-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'label-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'display-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'label-md': ['Plus Jakarta Sans', 'sans-serif'],
        'display-lg-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-xl': ['Plus Jakarta Sans', 'sans-serif'],
        'mono': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'headline-md': ['20px', { 'lineHeight': '28px', 'letterSpacing': '-0.005em', 'fontWeight': '600' }],
        'label-sm': ['11px', { 'lineHeight': '14px', 'letterSpacing': '0.04em', 'fontWeight': '700' }],
        'body-sm': ['12px', { 'lineHeight': '18px', 'letterSpacing': '0.01em', 'fontWeight': '400' }],
        'body-md': ['14px', { 'lineHeight': '22px', 'letterSpacing': '0em', 'fontWeight': '400' }],
        'label-lg': ['14px', { 'lineHeight': '20px', 'letterSpacing': '0.005em', 'fontWeight': '600' }],
        'display-lg': ['40px', { 'lineHeight': '48px', 'letterSpacing': '-0.02em', 'fontWeight': '800' }],
        'body-lg': ['16px', { 'lineHeight': '26px', 'letterSpacing': '0em', 'fontWeight': '400' }],
        'label-md': ['12px', { 'lineHeight': '16px', 'letterSpacing': '0.02em', 'fontWeight': '600' }],
        'display-lg-mobile': ['32px', { 'lineHeight': '40px', 'letterSpacing': '-0.02em', 'fontWeight': '800' }],
        'headline-lg': ['24px', { 'lineHeight': '32px', 'letterSpacing': '-0.01em', 'fontWeight': '700' }],
        'headline-xl': ['30px', { 'lineHeight': '38px', 'letterSpacing': '-0.015em', 'fontWeight': '700' }]
      }
    },
  },
  plugins: [],
}
