import React, { useState } from 'react';
import { useApp, CURRENCIES } from '../../context/AppContext';

export default function PaperReportModal() {
  const { state, closeReportModal, formatMoney } = useApp();
  const [copied, setCopied] = useState(false);

  if (!state.activeReportModal) return null;

  const screen = state.activeReportModal;
  const curr = CURRENCIES[state.currency] || CURRENCIES.INR;

  let reportTitle = '';
  let reportContent = '';

  if (screen === 'today') {
    reportTitle = 'Today Rhythm & Workload Paper Report';
    reportContent = `===================================================
DAYTRACE OS // TODAY TELEMETRY REPORT
Date: Mon, Sep 21, 2026 · 08:42 AM
User: Arjun Mehta (PRO TIER)
Weather: 26°C · Clear | Flow: ✨ Active Flow
===================================================

[1] OVERVIEW METRICS:
- Planned Workload: 7h 30m
- Recorded Realtime: ${Math.floor(state.liveFocus.elapsedSeconds / 60)}m (${state.scheduleBlocks.find(b=>b.id==='sb3')?.percentDone || 46}% Pace)
- Done Milestones: ${state.scheduleBlocks.filter(b=>b.done).length} / ${state.scheduleBlocks.length} (${state.scheduleBlocks.length - state.scheduleBlocks.filter(b=>b.done).length} pending)
- Spent Today: ${formatMoney(state.moneyState.todayFlowINR)} (Breakfast & Transit)

[2] LIVE ACTIVE SESSION:
- Title: ${state.liveFocus.title}
- Focus Track: ${state.liveFocus.subtitle}
- Window: 09:00 - 10:30 AM (Streak #${state.liveFocus.streak})
- Time Logged: ${Math.floor(state.liveFocus.elapsedSeconds / 60)}m elapsed / ${state.liveFocus.totalMinutes}m target

[3] TODAY'S SCHEDULE BLOCKS:
${state.scheduleBlocks.map((b, i) => `  ${i + 1}. [${b.done ? 'DONE' : 'PENDING'}] ${b.time} — ${b.title} (${b.durationMinutes}m) [${b.category}]`).join('\n')}

===================================================
Generated by DayTrace Mobile OS · Local-First Vault
===================================================`;
  } else if (screen === 'money') {
    reportTitle = 'Monthly Consumption & Activity Ledger';
    reportContent = `===================================================
DAYTRACE OS // FINANCIAL AUDIT & EXPENSE DISPERSION
Cycle: September 2026 · Sync Status: SYNC LIVE
Currency: ${curr.code} (${curr.name})
===================================================

[1] CONSUMPTION HEALTH:
- Total Deployed: ${formatMoney(state.moneyState.totalDeployedINR)} (45.4% Utilized)
- Maximum Guardrail Cap: ${formatMoney(state.moneyState.maxCapINR)}
- Pace Delta: ${formatMoney(state.moneyState.paceDifferenceINR)} under projected pace
- Runway Left: ${formatMoney(state.moneyState.runwayLeftINR)} (${state.moneyState.daysLeftInCycle} days left in cycle)
- Today's Flow: ${formatMoney(state.moneyState.todayFlowINR)} (${state.moneyState.todayFlowCount} transactions)

[2] CATEGORY ALLOCATION:
${state.moneyState.categoryDistribution.map(c => `  • ${c.name}: ${formatMoney(c.amountINR)}`).join('\n')}

[3] ITEMIZED ACTIVITY LEDGER:
${state.moneyState.transactions.map(t => `  • ${t.dateGroup} | ${t.time}
    ${t.title} [${t.category}]: ${formatMoney(t.amountINR)}`).join('\n\n')}

===================================================
Verified Cryptographically by Secure Local Enclave
===================================================`;
  } else if (screen === 'timeline') {
    reportTitle = 'Temporal Drift & Schedule Verification';
    reportContent = `===================================================
DAYTRACE OS // TEMPORAL CADENCE LOG
Timeline Date: Mon, Sep 21, 2026
Sync Cadence: In Cadence · 09:42 AM
===================================================

[1] TEMPORAL DRIFT MATRIX:
- Planned Budget: 7h 30m Target Horizon
- Actual Recorded: 2h 14m Active Pacing
- Alignment Factor: 30% Aligned
- Active Target: Python Practice

[2] CONNECTED SCHEDULE THREAD:
${state.scheduleBlocks.map(b => `  • ${b.time} | ${b.title}
    Category: ${b.categoryTag || b.category} · Status: ${b.done ? 'COMPLETED' : (b.isActive ? 'IN PROGRESS' : 'SCHEDULED')}
    Details: ${b.subtitle || 'Standard routine'}`).join('\n\n')}

===================================================
End of Chronological Stream
===================================================`;
  } else {
    reportTitle = 'Visual Memory Hub Summary';
    reportContent = `===================================================
DAYTRACE OS // VISUAL MEMORY NEURAL SUMMARY
Items Indexed: ${state.memoryState.totalItems} Items
Daemons: Auto-OCR Active · L1 Synchronized
===================================================

[1] EXTRACTED TRACE CARDS:
${state.memoryState.items.map(m => `  • [${m.badge}] ${m.title} (${m.time})
    ${m.description || m.location || m.quote || ''}
    Tags: ${(m.tags || []).join(', ')}`).join('\n\n')}

===================================================
Generated by DayTrace Local Engine
===================================================`;
  }

  const handleCopy = () => {
    navigator.clipboard.writeText(reportContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(`
        <html>
          <head>
            <title>${reportTitle}</title>
            <style>
              body { font-family: 'Courier New', monospace; padding: 24px; white-space: pre-wrap; font-size: 13px; line-height: 1.5; color: #111; }
            </style>
          </head>
          <body>${reportContent}</body>
        </html>
      `);
      printWindow.document.close();
      printWindow.focus();
      printWindow.print();
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 backdrop-blur-sm p-4 animate-in fade-in duration-200">
      <div 
        className="w-full max-w-lg rounded-2xl bg-white border border-slate-200 shadow-2xl p-5 flex flex-col max-h-[85vh] space-y-4"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between border-b border-slate-100 pb-3">
          <div className="flex items-center gap-2">
            <span className="material-symbols-outlined text-primary text-[22px]">description</span>
            <h3 className="font-headline-md text-headline-md font-bold text-on-surface">
              Paper / TXT Report
            </h3>
          </div>
          <button 
            onClick={closeReportModal}
            className="w-8 h-8 rounded-full flex items-center justify-center text-on-surface-variant hover:bg-slate-100"
          >
            <span className="material-symbols-outlined text-[20px]">close</span>
          </button>
        </div>

        {/* Paper Container Preview */}
        <div className="flex-1 overflow-y-auto bg-slate-50 border border-slate-200/80 rounded-xl p-3.5 font-mono text-[11px] leading-relaxed text-slate-800 whitespace-pre-wrap selection:bg-indigo-100">
          {reportContent}
        </div>

        <div className="flex items-center justify-between pt-1 gap-2">
          <button
            onClick={handlePrint}
            className="flex items-center gap-1.5 px-4 py-2 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-700 font-label-md transition-colors"
          >
            <span className="material-symbols-outlined text-[18px]">print</span>
            Print Paper
          </button>

          <div className="flex gap-2">
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 px-4 py-2 rounded-xl bg-primary text-white font-label-md font-bold hover:bg-primary-container shadow-md shadow-primary/20 transition-all"
            >
              <span className="material-symbols-outlined text-[18px]">
                {copied ? 'check' : 'content_copy'}
              </span>
              {copied ? 'Copied to Clipboard' : 'Copy TXT'}
            </button>
            <button
              onClick={closeReportModal}
              className="px-4 py-2 rounded-xl border border-slate-200 text-slate-600 font-label-md hover:bg-slate-50"
            >
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
